module

public import proofs.OverlapCorrectedRAF.Source.KauffmanRepositoryModel
public import proofs.RAF.Concrete.SeedGateway

@[expose] public section

namespace OverlapCorrectedRAF.Source

open RAF RAF.Polymer RAF.Concrete

/-- The literal reversible reaction system generated by the public repository:
one base reaction per displayed-reaction channel, with catalysis attached to the
base channel and therefore shared by its ligation and cleavage orientations. -/
def repositoryCRS (n t : Nat) :
    ReversibleCRS (Molecule n) (RepositoryChannel n) where
  lhs := fun r => {r.1.1, r.1.2}
  rhs := fun r => {concatMolecule r.1.1 r.1.2 r.2.1}
  food := binaryFood n t

abbrev RepositoryCatalysis (n : Nat) :=
  Catalysis (Molecule n) (RepositoryChannel n)

/-- The source-faithful gateway necessity theorem.  It uses the repository's
display quotient rather than the split-position reaction catalogue. -/
theorem repository_raf_implies_seedOpen (n t : Nat)
    (C : RepositoryCatalysis n) (S : Finset (RepositoryChannel n))
    (hraf : IsRevRAF (repositoryCRS n t) C S) :
    RevSeedOpen (repositoryCRS n t) C :=
  rev_raf_implies_seedOpen _ _ _ hraf

/-- Expanded existential form used by the probability adapter. -/
theorem repository_raf_has_catalyzed_gateway (n t : Nat)
    (C : RepositoryCatalysis n) (S : Finset (RepositoryChannel n))
    (hraf : IsRevRAF (repositoryCRS n t) C S) :
    ∃ r : RepositoryChannel n,
      RevSeedReaction (repositoryCRS n t) r ∧ ∃ x : Molecule n, C x r :=
  repository_raf_implies_seedOpen n t C S hraf

end OverlapCorrectedRAF.Source
